#!/bin/bash
#supposed to be run from the root folder as `./tests/tests-launch`

tmpfile="./tests/tmp"
inputCurve="./tests/exampleInput"
inputCurve2="./tests/exampleInput2"
pyScript="./tests/outputTester.py"

./flp22-fun -i < $inputCurve > $tmpfile
diffres=$(diff $tmpfile $inputCurve)
rm $tmpfile
if [ "$diffres" == "" ]; then
    echo "Parameter -i works correctly - Test 1"
else
    echo "$diffres"
fi

./flp22-fun -i < $inputCurve2 > $tmpfile
diffres=$(diff $tmpfile $inputCurve2)
rm $tmpfile
if [ "$diffres" == "" ]; then
    echo "Parameter -i works correctly - Test 2"
else
    echo "$diffres"
fi

# lets test the key 5 times because it's RNG and all outputs w/ valid input should be ok
for i in {1..5}
do
    ./flp22-fun -k < $inputCurve > $tmpfile
    python3 $pyScript -k < $tmpfile
    if [ $? == 42 ]; then
        echo "Parameter -k seems to produce a valid-ish looking output - Test $i"
    else
        echo "FAIL Parameter -k seems to have produced something weird"
    fi
    rm $tmpfile
done

# do the same with the -s parameter
for i in {1..5}
do
    ./flp22-fun -s < ./tests/exampleS > $tmpfile
    python3 $pyScript -s < $tmpfile
    if [ $? == 43 ]; then
        echo "Parameter -s seems to produce a valid-ish looking signature - Test $i"
    else
        echo "FAIL Parameter -s seems to have produced something weird"
    fi
    rm $tmpfile
done

# test my own input w/ custom generated key
for i in {1..5}
do
    ./flp22-fun -s < ./tests/exampleS1 > $tmpfile
    python3 $pyScript -s < $tmpfile
    if [ $? == 43 ]; then
        echo "Parameter -s seems to produce a valid-ish looking signature with my custom key - Test $i"
    else
        echo "FAIL Parameter -s seems to have produced something weird"
    fi
    rm $tmpfile
done

# similarly, test the -v
./flp22-fun -v < ./tests/exampleV > $tmpfile
python3 $pyScript -vT < $tmpfile
if [ $? == 44 ]; then
    echo "Parameter -v seems to pass with expected input"
else
    echo "FAIL Parameter -v seems to have produced something weird"
fi
rm $tmpfile

# -v with custom generated input
./flp22-fun -v < ./tests/exampleV1 > $tmpfile
python3 $pyScript -vT < $tmpfile
if [ $? == 44 ]; then
    echo "Parameter -v seems to pass with my custom input - Test $i"
else
    echo "FAIL Parameter -v seems to have produced something weird"
fi
rm $tmpfile

# -v with custom generated input but its supposed to fail
./flp22-fun -v < ./tests/exampleV1False > $tmpfile
python3 $pyScript -vF < $tmpfile
if [ $? == 45 ]; then
    echo "Parameter -v seems to correctly fail with my custom wrong input - Test $i"
else
    echo "FAIL Parameter -v seems to have produced something weird"
fi
rm $tmpfile